// src/constants/booking.ts
export const CITIES = [
  'Ahmedabad', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 
  'Pune', 'Hyderabad', 'Jaipur', 'Surat', 'Vadodara', 'Rajkot',
  'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal',
  'Visakhapatnam', 'Pimpri-Chinchwad', 'Patna', 'Vadodara', 'Ghaziabad',
  'Ludhiana', 'Agra', 'Nashik', 'Ranchi', 'Faridabad', 'Meerut',
  'Kalyan-Dombivali', 'Vasai-Virar', 'Srinagar', 'Aurangabad', 'Dhanbad',
  'Amritsar', 'Allahabad', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior',
  'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Guwahati',
  'Chandigarh', 'Solapur', 'Hubli-Dharwad', 'Bareilly', 'Moradabad',
  'Mysore', 'Gurgaon', 'Aligarh', 'Jalandhar', 'Tiruchirappalli',
  'Bhubaneswar', 'Salem', 'Warangal', 'Guntur', 'Bhiwandi', 'Saharanpur',
  'Gorakhpur', 'Bikaner', 'Amravati', 'Noida', 'Jamshedpur', 'Bhilai',
  'Cuttack', 'Firozabad', 'Kochi', 'Nellore', 'Bhavnagar', 'Dehradun',
  'Durgapur', 'Asansol', 'Rourkela', 'Nanded', 'Kolhapur', 'Ajmer',
  'Gulbarga', 'Jamnagar', 'Ujjain', 'Loni', 'Siliguri', 'Jhansi',
  'Ulhasnagar', 'Nellore', 'Jammu', 'Sangli-Miraj', 'Belgaum', 'Mangalore',
  'Ambattur', 'Tirunelveli', 'Malegaon', 'Gaya', 'Jalgaon', 'Udaipur',
  'Maheshtala', 'Tiruppur', 'Davanagere', 'Kozhikode', 'Akola', 'Kurnool',
  'Rajpur Sonarpur', 'Bokaro', 'South Dumdum', 'Bellary', 'Patiala',
  'Gopalpur', 'Agartala', 'Bhagalpur', 'Muzaffarnagar', 'Bhatpara',
  'Panihati', 'Latur', 'Dhule', 'Rohtak', 'Korba', 'Bhilwara',
  'Berhampur', 'Muzaffarpur', 'Ahmednagar', 'Mathura', 'Kollam',
  'Avadi', 'Kadapa', 'Kamarhati', 'Bilaspur', 'Shahjahanpur',
  'Satara', 'Bijapur', 'Rampur', 'Shivamogga', 'Chandrapur', 'Junagadh',
  'Thrissur', 'Alwar', 'Bardhaman', 'Kulti', 'Kakinada', 'Nizamabad',
  'Parbhani', 'Tumkur', 'Hisar', 'Ozhukarai', 'Bihar Sharif', 'Panipat',
  'Darbhanga', 'Bally', 'Aizawl', 'Dewas', 'Ichalkaranji', 'Tirupati',
  'Karnal', 'Bathinda', 'Rampur', 'Shivpuri', 'Ratlam', 'Hapur',
  'Arrah', 'Anantapur', 'Karimnagar', 'Parbhani', 'Etawah', 'Bharatpur',
  'Begusarai', 'New Delhi', 'Chandigarh', 'Daman', 'Diu', 'Puducherry',
  'Lakshadweep', 'Andaman and Nicobar Islands'
];

export const AIRPORTS = [
  'Ahmedabad Airport (AMD)', 'Mumbai Airport (BOM)', 'Delhi Airport (DEL)',
  'Bangalore Airport (BLR)', 'Chennai Airport (MAA)', 'Kolkata Airport (CCU)',
  'Hyderabad Airport (HYD)', 'Pune Airport (PNQ)', 'Jaipur Airport (JAI)',
  'Lucknow Airport (LKO)', 'Varanasi Airport (VNS)', 'Amritsar Airport (ATQ)',
  'Guwahati Airport (GAU)', 'Patna Airport (PAT)', 'Ranchi Airport (IXR)',
  'Bhubaneswar Airport (BBI)', 'Vijayawada Airport (VGA)', 'Coimbatore Airport (CJB)',
  'Kochi Airport (COK)', 'Thiruvananthapuram Airport (TRV)', 'Mangalore Airport (IXE)',
  'Goa Airport (GOI)', 'Nagpur Airport (NAG)', 'Indore Airport (IDR)',
  'Bhopal Airport (BHO)', 'Raipur Airport (RPR)', 'Jabalpur Airport (JLR)',
  'Aurangabad Airport (IXU)', 'Nashik Airport (ISK)', 'Kolhapur Airport (KLH)',
  'Surat Airport (STV)', 'Vadodara Airport (BDQ)', 'Rajkot Airport (RAJ)',
  'Bhavnagar Airport (BHU)', 'Jamnagar Airport (JGA)', 'Kandla Airport (IXY)',
  'Porbandar Airport (PBD)', 'Bhuj Airport (BHJ)', 'Mundra Airport (MUX)',
  'Deesa Airport (DES)', 'Mehsana Airport (MHS)', 'Gandhinagar Airport (GND)',
  'Anand Airport (AND)', 'Nadiad Airport (NDD)', 'Bharuch Airport (BHC)',
  'Valsad Airport (VLS)', 'Vapi Airport (VPI)', 'Silvassa Airport (SIL)',
  'Daman Airport (NMB)', 'Diu Airport (DIU)', 'Porbandar Airport (PBD)',
  'Bhavnagar Airport (BHU)', 'Rajkot Airport (RAJ)', 'Jamnagar Airport (JGA)',
  'Kandla Airport (IXY)', 'Mundra Airport (MUX)', 'Deesa Airport (DES)',
  'Mehsana Airport (MHS)', 'Gandhinagar Airport (GND)', 'Anand Airport (AND)',
  'Nadiad Airport (NDD)', 'Bharuch Airport (BHC)', 'Valsad Airport (VLS)',
  'Vapi Airport (VPI)', 'Silvassa Airport (SIL)', 'Daman Airport (NMB)',
  'Diu Airport (DIU)', 'Porbandar Airport (PBD)', 'Bhavnagar Airport (BHU)',
  'Rajkot Airport (RAJ)', 'Jamnagar Airport (JGA)', 'Kandla Airport (IXY)',
  'Mundra Airport (MUX)', 'Deesa Airport (DES)', 'Mehsana Airport (MHS)',
  'Gandhinagar Airport (GND)', 'Anand Airport (AND)', 'Nadiad Airport (NDD)',
  'Bharuch Airport (BHC)', 'Valsad Airport (VLS)', 'Vapi Airport (VPI)',
  'Silvassa Airport (SIL)', 'Daman Airport (NMB)', 'Diu Airport (DIU)'
];

export const PACKAGES = [
  '4 Hours / 40 KM', '8 Hours / 80 KM', '12 Hours / 120 KM', 'Full Day'
];